# fly.toml app configuration file generated for pybrd on 2023-10-08T23:01:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pybrd"
primary_region = "sea"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
